export type StartHereSubsection = {
  title: string
  body: string
  analogy?: { label: string; text: string }
}

export type StartHereSection = {
  id: string
  title: string
  subtitle?: string
  defaultOpen?: boolean
  body?: string
  subsections?: StartHereSubsection[]
  callouts?: { title: string; body: string }[]
  walletSidebar?: boolean
  disclaimer?: boolean
}

export const START_HERE_CALLOUTS = {
  doneNotDead: {
    title: 'Done ≠ dead',
    body: 'Quiet doesn\'t mean abandoned. A repo marked Done has finished what it set out to do — especially supply-lock repos, where quiet is the whole point. Check the status badge before assuming low activity is a problem.',
  },
  fNotScam: {
    title: 'F ≠ scam',
    body: 'A low or F grade on Holder economics is a rubric result, not a red flag. Infra and indirect repos are essential to the ecosystem but will always score low here by design — that\'s how the category works, not a sign of trouble.',
  },
  cvEarned: {
    title: 'CV is earned, not just held',
    body: 'CV (conviction) comes from staking $CLAWD, not just holding it in your wallet. A CV burn and a $CLAWD burn are different things — CV is governance weight, $CLAWD burn is permanent supply reduction.',
  },
} as const

export const START_HERE_ANALOGIES: { label: string; text: string }[] = [
  {
    label: 'Commits',
    text: 'Think of commits like punches on a time card — this shows how many the team clocked in during the selected window.',
  },
  {
    label: 'Burn',
    text: 'Burning $CLAWD is like shredding cash — it\'s gone for good, and everyone else\'s share of what\'s left gets a little bigger.',
  },
  {
    label: 'Supply-lock (Done)',
    text: 'Like a savings account that\'s been sealed shut — the money\'s still there, it\'s just not moving. Quiet means the seal is holding, not that someone walked away.',
  },
  {
    label: 'Live AI vs Launch baseline',
    text: 'Launch baseline is the report card from opening day. Live AI is today\'s pop quiz — a fresh read on the repo\'s current state.',
  },
  {
    label: 'Builder standards',
    text: 'Think of it like a kitchen health inspection — it\'s checking process and safety, not how good the food tastes.',
  },
  {
    label: 'Holder economics tiers',
    text: 'Direct apps hand $CLAWD holders something to use right now; supply-lock and burn repos shrink the total pie; infra keeps the lights on for everyone else.',
  },
  {
    label: 'Burn vs supply-lock',
    text: 'Burn is shredding the cash. Supply-lock is putting it in a safe — still exists, just not spendable. Both take it off the street.',
  },
  {
    label: 'CV (conviction)',
    text: 'Think of it like loyalty points that only accrue while your $CLAWD is staked, not just sitting in your wallet.',
  },
]

export const START_HERE_CHECKLIST = {
  intro: 'New here? Try these three things:',
  items: [
    'Set the time window to 7d',
    'Try the Burn apps filter',
    'Open one repo card and read its full scorecard',
  ],
} as const

export const START_HERE_GLOSSARY: { term: string; definition: string }[] = [
  { term: 'Repo', definition: 'One project on GitHub — a labeled folder holding all the code for one app or tool' },
  { term: 'Org (Organization)', definition: 'A group GitHub account that owns multiple repos — here, that\'s clawdbotatg' },
  { term: 'Commit', definition: 'One saved code change, like hitting save on a document; each has a timestamp' },
  { term: 'Push', definition: 'Sending commits to GitHub so they\'re visible to others' },
  { term: 'Holder Economics', definition: 'The site\'s score for whether a repo creates value for $CLAWD holders — graded A–F' },
  { term: 'Builder Standards', definition: 'The site\'s score for how safely and transparently a repo is being built' },
  { term: 'Builder Activity', definition: 'The site\'s score for recent commit volume in the selected time window' },
  { term: 'Burn', definition: 'Permanently destroying $CLAWD tokens, shrinking total supply' },
  { term: 'Supply-lock', definition: 'Removing $CLAWD from circulation without destroying it — locked, not gone' },
  {
    term: 'Done',
    definition:
      'A status badge meaning the repo finished its job; quiet is expected and correct, especially for supply-lock repos — Done never means dead',
  },
  { term: 'Shipping', definition: 'A status badge for a repo actively releasing new features or updates' },
  { term: 'Stable', definition: 'A status badge for a repo working as intended with light, healthy upkeep' },
  {
    term: 'Launch Baseline',
    definition: 'The activity level recorded when a repo first went live — the comparison point for current scores',
  },
  {
    term: 'Live AI',
    definition: 'A score generated by Claude reading the repo\'s current state — not a human review in real time',
  },
  {
    term: 'Chronicle',
    definition: 'The site\'s reference doc summarizing a repo\'s history, purpose, and stated lifecycle',
  },
  { term: 'Discussion', definition: 'A repo filter showing projects with community-submitted context notes' },
  {
    term: 'Rescore',
    definition: 'A paid action that triggers a fresh Live AI score; the fee goes toward buying and burning $CLAWD',
  },
  {
    term: 'Clawd/CV Perks',
    definition: 'A repo filter showing projects that gate features behind holding $CLAWD or staked CV',
  },
  { term: 'Burn Apps', definition: 'A repo filter showing projects tied to $CLAWD burn events or mechanics' },
  {
    term: '24h / 7d / 30d / 60d window',
    definition: 'The time range for counting commits — toggle to change what "recent" means',
  },
  { term: '$CLAWD', definition: 'The token tracked by this site, on the Base blockchain' },
  {
    term: 'CV (Conviction)',
    definition:
      'Earned by staking $CLAWD over time, not just holding it — used for perks and governance weight, separate from token supply',
  },
  { term: 'Base', definition: 'The blockchain network $CLAWD lives on — see the wallet note if this is new' },
  {
    term: 'Infrastructure (Infra)',
    definition:
      'Repos supporting the ecosystem behind the scenes — no direct holder impact, but necessary for everything else',
  },
]

export const START_HERE_DISCLAIMER = [
  'This site is a community project, not an official product of any company or development team.',
  'Scores shown here — whether Live AI or Launch baseline — are interpretive assessments, not audits, guarantees, or professional financial evaluations. They reflect one methodology applied at a point in time and may not capture every relevant factor.',
  'Nothing on this site is financial advice. Holding, buying, or selling $CLAWD or any other token involves risk. Do your own research and consult a qualified financial professional before making investment decisions.',
  'Community context submissions are user-generated and have not been independently verified. Discussion notes reflect community sentiment, not factual endorsement.',
  'The Build Report is not affiliated with, endorsed by, or responsible for the clawdbotatg organization or any of its projects.',
] as const

export const START_HERE_TOC = [
  { href: '#sh-what', label: 'What is this site?' },
  { href: '#sh-github', label: 'GitHub for you' },
  { href: '#sh-scores', label: 'The grades' },
  { href: '#sh-walkthrough', label: '3-minute walkthrough' },
  { href: '#sh-token', label: 'CLAWD & CV' },
  { href: '#sh-glossary', label: 'Glossary' },
  { href: '#sh-wallet', label: 'Wallets & Rescore' },
  { href: '#sh-disclaimer', label: 'Disclaimer' },
] as const

export const START_HERE_SECTIONS: StartHereSection[] = [
  {
    id: 'sh-what',
    title: 'What is this site?',
    subtitle: 'What The Build Report tracks and why it exists',
    defaultOpen: true,
    body: 'The Build Report tracks the GitHub activity of the clawdbotatg organization — the team building tools around the $CLAWD token — and scores each repo on three things: does it help holders, is it being built carefully, and is anyone actually working on it? This is a community project, not an official product of any company, so every score here is interpretive, not a guarantee. The goal is simple: let $CLAWD holders and curious newcomers follow development without needing to read a line of code. You don\'t need a GitHub account, a wallet, or any technical background to use anything on this site.',
  },
  {
    id: 'sh-github',
    title: 'What is GitHub (for you)?',
    subtitle: 'Repos, commits, and what activity numbers mean',
    callouts: [START_HERE_CALLOUTS.doneNotDead],
    subsections: [
      {
        title: 'The 60-second version',
        body: 'GitHub is where software teams store and share their code — like Google Drive, but built for building apps. A repo (repository) is one project, stored in its own labeled folder. An org (organization) is a group account that owns multiple repos, the way a company owns multiple products — here that\'s clawdbotatg. A commit is one saved update to the code, like hitting save on a document, timestamped and described. A push sends those commits to GitHub so others can see them; several commits often travel in one push.',
      },
      {
        title: 'What activity numbers actually mean',
        body: 'The site counts commits over 24h, 7d, 30d, and 60d windows to show whether work is happening right now, recently, or over time. More commits isn\'t automatically better — a repo that got one commit last month to fix something important is still healthy. And zero commits isn\'t automatically bad: a repo marked Done has finished its job and is supposed to go quiet, especially supply-lock repos. Shipping means new features are actively landing; Stable means the repo is doing its job with light, healthy upkeep; Done means the work is finished on purpose. None of those three is a red flag by itself.',
        analogy: START_HERE_ANALOGIES[0],
      },
    ],
  },
  {
    id: 'sh-scores',
    title: 'The grades, plain English',
    subtitle: 'Holder economics, Shipping leverage, Builder standards, and Builder activity',
    callouts: [START_HERE_CALLOUTS.fNotScam, START_HERE_CALLOUTS.doneNotDead],
    subsections: [
      {
        title: 'Holder economics',
        body: 'This asks one question: does this repo create real value for people who hold $CLAWD? It applies to the repos that touch the token directly — direct apps that use or reward $CLAWD, and supply-lock repos that remove tokens from circulation. Their grades are averaged into the Holder economics Ecosystem Grade at the top. A low or F grade here means the repo doesn\'t score well on this one rubric — it\'s an interpretive site score, not a scam alarm. Infrastructure and tooling repos aren\'t judged on this rubric at all — they get graded on Shipping leverage instead (next).',
        analogy: START_HERE_ANALOGIES[5],
      },
      {
        title: 'Shipping leverage',
        body: 'This is the second lens on holder value, for the behind-the-scenes repos — infrastructure, tooling, and R&D — that don\'t burn or lock $CLAWD themselves. It asks: how much does this work multiply the builder\'s ability to ship the apps that DO benefit holders? These repos used to be scored per-card but left out of the top averages, which was confusing. Now they roll up into their own Shipping leverage Ecosystem Grade at the top, paired with Holder economics as two lenses on the same question. A strong grade here means the plumbing is speeding up holder-facing shipping, even with zero direct burns in the repo.',
        analogy: START_HERE_ANALOGIES[5],
      },
      {
        title: 'Builder standards',
        body: 'This asks: is this repo being built carefully? It looks at safety practices, whether the code has tests, and how clear the documentation is. A lower score usually just means the repo is early-stage or under-documented, which is common for fast-moving projects. It\'s a snapshot of current polish, not a judgment on the team or the idea behind the repo.',
        analogy: START_HERE_ANALOGIES[4],
      },
      {
        title: 'Builder activity',
        body: 'This asks: is anyone actually working on this? It\'s based on commit counts across the org in your selected time window, measured against activity benchmarks. This one is an Ecosystem Grade only — it shows in the grade cards at the top of the page, not on individual repo cards. Individual repos instead show their own commit count for the window. A quiet stretch can still be completely healthy: a Done supply-lock repo, for example, is supposed to go quiet once its job is finished. Quiet doesn\'t mean dead. Always check the status badge before assuming low activity is a problem.',
        analogy: START_HERE_ANALOGIES[2],
      },
    ],
  },
  {
    id: 'sh-walkthrough',
    title: 'How to read the homepage in 3 minutes',
    subtitle: 'Four grade cards → activity snapshot → repo list',
    subsections: [
      {
        title: 'Step 1 — The four grade cards at the top',
        body: 'The top of the page shows four Ecosystem Grades — the org-wide averages for Builder activity, Builder standards, and the two holder-value lenses: Holder economics (repos that touch $CLAWD directly) and Shipping leverage (the tooling that helps ship them). Each is its own lens on the same set of repos, so a project can score well on one and poorly on another, and that\'s normal, not a red flag. Use the 24h / 7d / 30d / 60d toggle to change the time window. If a card looks low, don\'t stop there: open the repo list (Step 3) to see which specific repos are pulling the average down, and why.',
      },
      {
        title: 'Step 2 — Activity snapshot',
        body: 'This shows commit counts for the org, using the same 24h / 7d / 30d / 60d window you picked above. Shorter windows are noisy — a quiet 24h is normal on weekends or for mature repos. Widen to 7d or 30d for a fairer read on whether real work is happening. A flat line here is a scheduling artifact, not a verdict; it never means abandoned on its own.',
      },
      {
        title: 'Step 3 — The repo list',
        body: 'Each row is one project. Each card shows two Repo Grades — Holder economics and Builder standards — plus that repo\'s commit count for the window, its last-activity timestamp, and a status badge (Shipping, Stable, or Done). Use the filters above the list to narrow things down: Burn apps for repos tied to $CLAWD burns, Clawd/CV perks for repos that gate features behind holding, Discussion for repos with community-submitted notes. Sort by Recent, Most active, or Grades. Click any row to expand its full scorecard. If your only question is "are they still building?" — sort by Most active, set the window to 7d, and start there.',
      },
    ],
  },
  {
    id: 'sh-token',
    title: 'CLAWD, CV, burn & supply-lock',
    subtitle: 'Minimum token vocabulary to read the dashboard',
    callouts: [START_HERE_CALLOUTS.cvEarned, START_HERE_CALLOUTS.doneNotDead],
    body: '$CLAWD is the token itself, live on Base. CV (conviction) is different — it\'s earned by staking $CLAWD, not just holding it in a wallet. A CV burn and a $CLAWD burn are also different things: burning $CLAWD destroys tokens and shrinks total supply; CV works more like governance weight or attention, not a supply mechanic.\n\nOn the site, a direct burn permanently destroys $CLAWD supply. A supply-lock instead removes tokens from circulation without destroying them — locked up, not gone. Both reduce what\'s trading freely, which is why a supply-lock repo going quiet and marked Done is a success state, not abandonment: the lock is holding and the job is finished.\n\nSome repos gate features behind holding $CLAWD or CV — use the Clawd/CV perks filter in the repo list to find them. None of this is required to read scores or browse the site.',
  },
  {
    id: 'sh-glossary',
    title: 'Glossary',
    subtitle: 'Terms in the order you\'re likely to hit them on the site',
  },
  {
    id: 'sh-wallet',
    title: 'A note on wallets, ETH & Rescore',
    subtitle: 'Only matters if you want Rescore or holder-gated features',
    walletSidebar: true,
    body: 'A crypto wallet, like MetaMask or Coinbase Wallet, is a software account that holds tokens — think of it as a digital ID and pocket combined. ETH (Ethereum) is a separate token used to pay for actions on many blockchains; even though $CLAWD lives on Base, small ETH fees still show up for on-chain transactions like Rescore.\n\nRescore costs 0.000008 ETH. That fee buys $CLAWD on the open market and burns it, so paying to rescore also benefits every other holder. Rescore and some holder-gated features require a wallet holding at least 10M $CLAWD.\n\nIf you don\'t have a wallet or ETH, you can still read every score, use every filter, and browse the Chronicle — Rescore is optional, never required to access the site.\n\nFor help setting up a wallet or buying ETH, search "how to set up a crypto wallet" — that\'s outside the scope of this guide.',
  },
  {
    id: 'sh-disclaimer',
    title: 'Disclaimer',
    disclaimer: true,
  },
]
